### PR TITLE
Use netlink-packet-route bitflag API

### PR DESCRIPTION
**Pull request by little-dude**
Update `rtnetlink` to use https://github.com/rust-netlink/netlink-packet-route/pull/106

### CODE REVIEW

**Comment by wllenyj** [comment]
welcome back.

**Comment by cathay4t** [comment]
I have release `netlink-packet-route 0.20.0` which changes the changes of bitflag, please change Cargo.toml to use that.

**Comment by little-dude** [comment]
done, @cathay4t!

**Review by mwanner — APPROVED** [review]
I looked into the same and came up with mostly equivalent changes. This PR is more thorough and adjusts comments, too.

Can we please get this merged and get a new version of rtnetlink released?

**Review by wllenyj — APPROVED** [review]

**Pull request merged**
