### PR TITLE
Added XFRM tunnel virtual interface creation.

### PR DESCRIPTION
**Pull request by mcr**
Signed-off-by: Michael Richardson <mcr@sandelman.ca>

### CODE REVIEW

**Comment by cathay4t** [comment]
Could you fix the CI?

**Comment by mcr** [comment]
> Could you fix the CI?

It requires the updates to netlink-packet-route, which is not merged.  I would have to do something specific in the CI to request that version/branch, which then we'd have to back-out.
https://github.com/rust-netlink/netlink-packet-route/pull/9 has the rustfmt fixes, can we merge that first and then that probably deals with most issues?

**Comment by mcr** [comment]
I'm seeing this for main at this point, and after rebasing, I see the same errors locally.  Perhaps the CI system will work okay.

````
obiwan-[trentonio/rust-netlink/rtnetlink](2.6.6) mcr 10138 %cargo test
   Compiling rtnetlink v0.12.0 (/ssw/projects/trentonio/rust-netlink/rtnetlink)
    Finished test [unoptimized + debuginfo] target(s) in 33.33s
     Running unittests src/lib.rs (target/debug/deps/rtnetlink-8e6daf046ce7c0bf)

running 5 tests
test traffic_control::test::test_get_traffic_classes_filters_and_chains ... ignored
test traffic_control::add_qdisc::test::test_new_qdisc ... FAILED
test traffic_control::add_filter::test::test_new_filter ... FAILED
test link::test::create_get_delete_wg ... FAILED
test traffic_control::test::test_get_qdiscs ... ok

failures:

---- traffic_control::add_qdisc::test::test_new_qdisc stdout ----
thread 'traffic_control::add_qdisc::test::test_new_qdisc' panicked at 'called `Result::unwrap()` on an `Err` value: NamespaceError("Error child result: 1")', src/traffic_control/add_qdisc.rs:109:59

---- traffic_control::add_filter::test::test_new_filter stdout ----
thread 'traffic_control::add_filter::test::test_new_filter' panicked at 'called `Result::unwrap()` on an `Err` value: NamespaceError("Error child result: 1")', src/traffic_control/add_filter.rs:195:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- link::test::create_get_delete_wg stdout ----
thread 'link::test::create_get_delete_wg' panicked at 'assertion failed: handle.is_ok()', src/link/test.rs:18:5


failures:
    link::test::create_get_delete_wg
    traffic_control::add_filter::test::test_new_filter
    traffic_control::add_qdisc::test::test_new_qdisc

test result: FAILED. 1 passed; 3 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.02s
````

**Comment by mcr** [comment]
@cathay4t can you poke/approve the CI run?

**Comment by cathay4t** [comment]
I have amended your patch by command `cargo fmt` to get the CI happy.

Merged!
Thanks for the contribution!

**Review by cathay4t — APPROVED** [review]

**Pull request merged**
