### PR TITLE
FreeBSD support

### PR DESCRIPTION
**Pull request by ydirson**
rtnetlink has 2 problems building on FreeBSD:
* no support for Linux namespaces and traffic control, addressed in first commit
* lack of `AddressFamily::Bridge` in `netlink-packet-route`, addressed in second commit

I originally thought about hiding namespaces and traffic control behind a `ns` feature, what do you think?

That second point brings me back to my original suggestion of having enum values defined once, regardless of target platform support.

### CODE REVIEW

**Comment by cathay4t** [comment]
@ydirson Please fix the CI failure.

Meanwhile, please include https://github.com/rust-netlink/netlink-packet-route/blob/main/.github/workflows/build.yml to this PR, so we know this project can actually compile on FreeBSD. (You may only keep `x86_64-unknown-freebsd` and `x86_64-unknown-linux-gnu`).

Thank you!

**Comment by ydirson** [comment]
> @ydirson Please fix the CI failure.
> 
> Meanwhile, please include https://github.com/rust-netlink/netlink-packet-route/blob/main/.github/workflows/build.yml to this PR, so we know this project can actually compile on FreeBSD. (You may only keep `x86_64-unknown-freebsd` and `x86_64-unknown-linux-gnu`).

The libc support still has not been merged, so this will not build yet out of the fox on freebsd.  Things more very slowly there, but it's not clear if I should resubmit my patch for 0.2 instead but protected by a feature flag.

**Comment by ydirson** [comment]
> @ydirson Please fix the CI failure.

I'm unsure how to handle examples that can only build under a given `cfg()`, since examples (and tests etc) are implicitly discovered. I just cannot find any hint of cargo supporting this use-case.

I tried guarding the example code with `#[cfg(any(linux, android))]`, but that ends with a build failure when there is no valid `main()`.  Is the only way out to have an empty `main()` for unsupported configuration?

**Comment by cathay4t** [comment]
> > @ydirson Please fix the CI failure.
> 
> I'm unsure how to handle examples that can only build under a given `cfg()`, since examples (and tests etc) are implicitly discovered. I just cannot find any hint of cargo supporting this use-case.
> 
> I tried guarding the example code with `#[cfg(any(linux, android))]`, but that ends with a build failure when there is no valid `main()`. Is the only way out to have an empty `main()` for unsupported configuration?


Instead of `#[cfg(any(linux, android))]`, can we do `#[cfg(not(freebsd))]`, the former one ruled out some uknonw(e.g. fuchsia) from compiling this crate which might works well before.

**Comment by ydirson** [comment]
> Instead of `#[cfg(any(linux, android))]`, can we do `#[cfg(not(freebsd))]`, the former one ruled out some os(e.g. fuchsia) from compiling this crate which might works well before.

Done - that had to be `#[cfg(target_os = "freebsd")]`, though

**Comment by cathay4t** [comment]
@ydirson The 0.14.1 release contains this PR now. Thanks for the contribution!

**Pull request merged**
