### PR TITLE
Provide the ability to set the underlying link ID when adding xfrm link types

### PR DESCRIPTION
**Pull request by zooknotic**
I would like to change the LinkAddRequest.xfrmtun() function to allow specifying the underlying interface link ID in addition to the if_id parameter. There isn't a convenient way of doing this without digging deeply into the created request with message_mut().

### CODE REVIEW

**Review by cathay4t — APPROVED** [review]

**Comment by cathay4t** [comment]
@zooknotic Thanks for the contribution! Please rebase.

**Comment by cathay4t** [comment]
Instead of breaking API, can we add a new function instead?

**Comment by zooknotic** [comment]
> Instead of breaking API, can we add a new function instead?

I suppose I can add another function like:
`pub fn xfrmtun_link(self, name: String, ifid: u32, link: u32)`
but it will add extra clutter and duplicate code.  Is it worth it?

I've rebased the commit to account for the InfoXfrmTun->InfoXfrm rename for now.

**Comment by cathay4t** [comment]
You may deprecate the old one and add new one.  I think duplicate code at this level is acceptable.

I really don't want to bump version for this simple reason. Bumping version is forcing all our user to change their `Cargo.toml`.

Meanwhile, please fix the CI failure on `cargo fmt` and `cargo clippy`.

**Comment by zooknotic** [comment]
@cathay4t I've pushed a new commit that should address your comments, but I haven't seen the github actions kick off again.  Please take a look when you have a chance.

**Pull request merged**
