### PR TITLE
Remove asserts in TC ( issue #16)

### PR DESCRIPTION
**Pull request by sophacles**
There are 2 commits in this PR:

1. Remove asserts that block reassignment completely. These asserts only checked that some message header value was the default value before doing an assignment a struct member. Reassignment should be allowed, so I've just removed them.
2. Update the u32 filter to return the new `Error::InvalidNla` error rather than panicking when the check condition fails.

### CODE REVIEW

**Comment by wllenyj** [comment]
Thanks for your work.
What case requires reassignment? The use of `assert` was to prevent the user from making mistakes and using the wrong API, such as calling `ingress().egress()`.

**Comment by sophacles** [comment]
Thanks for the feedback. I was also thinking about adding an `Error:AlreadySet` (or similar) for these cases. I chose this way because
my thinking is that doing something like `.ingress().egress()` isn't an error. It is inefficient, and may be the a symptom of a confused user, but the end result is a  valid message header with the egress bit set. Same for changing priority or parent. 

I don't have a specific case in mind at the moment, but I know I would be very frustrated if I had to work around this limitation. The TC requests don't have the `message_mut()` method like the `*AddrRequest` structs, but if it did, I would almost certainly do `req.message_mut().header.... = val` rather than restructuring my program to avoid reassignment.

Let me know what you think,  the "no failure" version is my preference, but having an error for these cases is easy enough to do.

**Comment by wllenyj** [comment]
@sophacles I just think is there a problem with how to use the API? So if you have to do this in your case, it is acceptable.

**Comment by cathay4t** [comment]
Assert is never a good idea in a rust library. I prefer the Result protect return of public function over assert.

If no objection, I would like to merge this patch and bump the version for API change.

**Review by cathay4t — APPROVED** [review]
LGTM

**Pull request merged**
