### PR TITLE
Get and set the bond port setting for the device

### PR DESCRIPTION
**Pull request by liangwen12year**

### CODE REVIEW

**Comment by liangwen12year** [comment]
I will temporarily keep the changes to `Cargo.toml` for the convenience of testing, but I will drop those changes once the PR is reviewed.

**Review by cathay4t — CHANGES_REQUESTED** [review]
The `get_bond_port_settings` works well, but the `set_bond_port_settings` is not working.

Changes required:
 1. In example code, please add comment with `ip link` command, so people can actually try your example.
 2. The `set_bond_port_settings.rs` has interface index, bond port name and match_name, they are overlapping each other. Please only keep one.
 3. The strace of `set_bond_port_settings` indicate a message of `nlmsg_type=NLMSG_ERROR` on reply, but your code never report a failure. Please investigate.
 4. ONLY REQUEST FOR REVIEW AFTER THE EXAMPLE CODE IS TESTED IN YOUR ENVIRONMENT. A simple try in my VM indicate your example code is not working.

**Comment by cathay4t** [comment]
I have published netlink-packet-route 0.16.0. Please use it and update this PR.

**Comment by liangwen12year** [comment]
> 4. ONLY REQUEST FOR REVIEW AFTER THE EXAMPLE CODE IS TESTED IN YOUR ENVIRONMENT. A simple try in my VM indicate your example code is not working.

Honestly, I indeed tested in the VM that I created before requesting for review (test result attached), but let me polish the code in the next step:

```
[root@wsfd-netdev77 examples]# ip -d a s eno4
5: eno4: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc mq master nm-bond state DOWN group default qlen 1000
    link/ether 24:6e:96:5e:e5:75 brd ff:ff:ff:ff:ff:ff promiscuity 0  allmulti 0 minmtu 68 maxmtu 9216 
    bond_slave state BACKUP mii_status DOWN link_failure_count 0 perm_hwaddr 24:6e:96:5e:e5:75 queue_id 0 prio 51 numtxqueues 8 numrxqueues 8 gso_max_size 65536 gso_max_segs 65535 tso_max_size 65536 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536 parentbus pci parentdev 0000:0a:00.1 
    altname enp10s0f1
    inet 178.162.22.108/16 scope global eno4
       valid_lft forever preferred_lft forever
[root@wsfd-netdev77 examples]# cargo run --example set_bond_port_settings -- eno4
   Compiling rtnetlink v0.12.0 (/root/rtnetlink)
    Finished dev [unoptimized + debuginfo] target(s) in 1.28s
     Running `/root/rtnetlink/target/debug/examples/set_bond_port_settings eno4`
NetlinkMessage { header: NetlinkHeader { length: 0, message_type: 0, flags: 5, sequence_number: 0, port_number: 0 }, payload: InnerMessage(NewLink(LinkMessage { header: LinkHeader { interface_family: 0, index: 5, link_layer_type: 0, flags: 1, change_mask: 1 }, nlas: [Info([SlaveKind(Bond), SlaveData(BondPort([QueueId(0), Prio(50)]))])] })) }
[root@wsfd-netdev77 examples]# ip -d a s eno4
5: eno4: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc mq master nm-bond state DOWN group default qlen 1000
    link/ether 24:6e:96:5e:e5:75 brd ff:ff:ff:ff:ff:ff promiscuity 0  allmulti 0 minmtu 68 maxmtu 9216 
    bond_slave state BACKUP mii_status DOWN link_failure_count 0 perm_hwaddr 24:6e:96:5e:e5:75 queue_id 0 prio 50 numtxqueues 8 numrxqueues 8 gso_max_size 65536 gso_max_segs 65535 tso_max_size 65536 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536 parentbus pci parentdev 0000:0a:00.1 
    altname enp10s0f1
    inet 178.162.22.108/16 scope global eno4
       valid_lft forever preferred_lft forever
[root@wsfd-netdev77 examples]#
```

**Comment by ffmancera** [comment]
Hi Gris,

I have taken a look to the existing code and I would like to reply to this review.

> The `get_bond_port_settings` works well, but the `set_bond_port_settings` is not working.
> 
> Changes required:
> 
>     1. In example code, please add comment with `ip link` command, so people can actually try your example.
> 
>     2. The `set_bond_port_settings.rs` has interface index, bond port name and match_name, they are overlapping each other. Please only keep one.
> 

I have noticed other examples are doing this. Sure, it should be possible to ask the user the ifindex directly.. but that doesn't seem intuitive even for an example. In case you want to use the ifindex directly, we should do the same in all the examples to be consistent.

>     3. The strace of `set_bond_port_settings` indicate a message of `nlmsg_type=NLMSG_ERROR` on reply, but your code never report a failure. Please investigate.
> 

That is expected. If you check `man 7 netlink` you can find:

```
Netlink is not a reliable protocol.  It tries its best to deliver a message to its destination(s), but may drop messages when an out-of-memory condition or other error occurs.  For reliable transfer the sender can request  an
       acknowledgement  from  the receiver by setting the NLM_F_ACK flag.  An acknowledgement is an NLMSG_ERROR packet with the error field set to 0.
```

>     4. ONLY REQUEST FOR REVIEW AFTER THE EXAMPLE CODE IS TESTED IN YOUR ENVIRONMENT. A simple try in my VM indicate your example code is not working.

What problem did you find? It works well for me.

**Comment by cathay4t** [comment]
Tested in my VM. Works well. Thanks!

Change requests:
 * Try no change `LinkSetRequst`, just check whether message contains bond port config or not and update message type and flag accordingly.
 * Function name should follow the https://doc.rust-lang.org/1.0.0/style/style/naming/README.html , use `fn bond_port`
 * Please remove `fn up()` from `BondPortSetRequest`.

**Comment by cathay4t** [comment]
On a second review of this PR, I think the better design is to expand `LinkHandle` instead of chaining a request under  `LinkSetRequest`, reason:

 * User cannot store `LinkSetRequest` (e.g. link up) into `BondPortSetRequest` because they using different flag and message type.
 * `BondPortSetRequest` is not a subnet of `LinkSetRequest`.
 * This simplify the design.


I have amended your patch and posted to https://github.com/cathay4t/rtnetlink/tree/add_bond_port_support

Please review it and polish it for this PR.

**Comment by liangwen12year** [comment]
> On a second review of this PR, I think the better design is to expand `LinkHandle` instead of chaining a request under `LinkSetRequest`, reason:
> 
> * User cannot store `LinkSetRequest` (e.g. link up) into `BondPortSetRequest` because they using different flag and message type.
> * `BondPortSetRequest` is not a subnet of `LinkSetRequest`.
> * This simplify the design.
> 
> I have amended your patch and posted to https://github.com/cathay4t/rtnetlink/tree/add_bond_port_support
> 
> Please review it and polish it for this PR.

I reviewed it, maybe it is not necessary to put the `index` into the struct `BondPortSetRequest` and we can assign `message.header.index = index` in the `BondPortSetRequest::new()`, but it sounds like the personal taste (personal opinion).

**Comment by liangwen12year** [comment]
> On a second review of this PR, I think the better design is to expand `LinkHandle` instead of chaining a request under `LinkSetRequest`, reason:
> 
> * User cannot store `LinkSetRequest` (e.g. link up) into `BondPortSetRequest` because they using different flag and message type.
> * `BondPortSetRequest` is not a subnet of `LinkSetRequest`.
> * This simplify the design.
> 
> I have amended your patch and posted to https://github.com/cathay4t/rtnetlink/tree/add_bond_port_support
> 
> Please review it and polish it for this PR.

I reviewed, it looks quite good.

**Review by cathay4t — APPROVED** [review]

**Pull request merged**
